POST http://localhost:3001/api/quizzes
Content-Type: application/json

{
  "quizname": "All about ducks",
  "questions": [
    {
      "question": "How many legs ducks have",
      "correctAnswer": 2,
      "falseAnswer1": 4,
      "falseAnswer2": 6
    }
]
}